from __future__ import annotations

import importlib
import json
import os
import sqlite3
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Callable

from .config import settings


@dataclass(frozen=True)
class IndexJob:
    id: str
    job_type: str
    path: str
    status: str
    attempts: int
    created_at: str
    started_at: str | None
    completed_at: str | None
    last_error: str | None


class JobStore:
    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as con:
            con.execute("""CREATE TABLE IF NOT EXISTS jobs (
                id TEXT PRIMARY KEY, job_type TEXT NOT NULL, path TEXT NOT NULL,
                payload_json TEXT NOT NULL, status TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL, started_at TEXT, completed_at TEXT, last_error TEXT
            )""")

    def _connect(self):
        return sqlite3.connect(self.path, timeout=30)

    def enqueue(self, job_type: str, path: str, payload: dict[str, Any] | None = None) -> str:
        job_id = str(uuid.uuid4()); now = datetime.now(timezone.utc).isoformat()
        with self._connect() as con:
            con.execute("INSERT INTO jobs(id,job_type,path,payload_json,status,attempts,created_at) VALUES(?,?,?,?,?,?,?)", (job_id, job_type, path, json.dumps(payload or {}), "PENDING", 0, now))
        return job_id

    def get(self, job_id: str) -> IndexJob | None:
        with self._connect() as con:
            row = con.execute("SELECT id,job_type,path,status,attempts,created_at,started_at,completed_at,last_error FROM jobs WHERE id=?", (job_id,)).fetchone()
        return IndexJob(*row) if row else None

    def claim(self) -> tuple[IndexJob, dict[str, Any]] | None:
        """Atomically claim work and requeue stale RUNNING jobs after a worker crash."""
        cutoff = datetime.now(timezone.utc) - timedelta(seconds=max(settings.worker_lease_seconds, 1))
        cutoff_iso = cutoff.isoformat()
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as con:
            con.execute("BEGIN IMMEDIATE")
            row = con.execute(
                "SELECT id,job_type,path,status,attempts,created_at,started_at,completed_at,last_error,payload_json "
                "FROM jobs WHERE status='PENDING' OR (status='RUNNING' AND started_at IS NOT NULL AND started_at<=?) "
                "ORDER BY created_at LIMIT 1",
                (cutoff_iso,),
            ).fetchone()
            if not row:
                con.rollback(); return None
            con.execute("UPDATE jobs SET status='RUNNING', attempts=attempts+1, started_at=?, completed_at=NULL, last_error=NULL WHERE id=?", (now,row[0])); con.commit()
        return IndexJob(row[0],row[1],row[2],"RUNNING",row[4]+1,row[5],now,None,None), json.loads(row[9])

    def record_external(self, job_id: str, job_type: str, path: str, payload: dict[str, Any]) -> str:
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as con:
            con.execute(
                "INSERT OR REPLACE INTO jobs(id,job_type,path,payload_json,status,attempts,created_at) VALUES(?,?,?,?,?,?,?)",
                (job_id, job_type, path, json.dumps(payload), "EXTERNAL", 0, now),
            )
        return job_id

    def finish(self, job_id: str, success: bool, error: str | None = None) -> None:
        with self._connect() as con:
            con.execute("UPDATE jobs SET status=?, completed_at=?, last_error=? WHERE id=?", ("SUCCEEDED" if success else "FAILED", datetime.now(timezone.utc).isoformat(), error[:4000] if error else None, job_id))


class TinyQueueAdapter:
    """Bridge to the separate portfolio TinyQueue with a durable local worker fallback.

    Set TINYQUEUE_IMPORT=module:function. The function receives (job_type, payload_dict)
    and returns a job id. Without it, JobStore persists jobs and localrag.worker consumes them.
    """
    def __init__(self, external_target: str | None = None):
        self.external_target = external_target or os.getenv("TINYQUEUE_IMPORT")
        self.store = JobStore(settings.job_db_path)

    def submit_index(self, path: Path) -> str:
        payload = {"job_id": str(uuid.uuid4()), "path": str(path), "data_root": str(path)}
        if self.external_target:
            module_name, attr = self.external_target.split(":",1)
            enqueue: Callable[..., Any] = getattr(importlib.import_module(module_name), attr)
            external_id = str(enqueue("index_documents", payload) or payload["job_id"])
            return self.store.record_external(external_id, "index_documents", str(path), payload)
        # Persist with a stable job id generated by JobStore; caller only needs this identifier.
        return self.store.enqueue("index_documents", str(path), payload)

    def get(self, job_id: str) -> IndexJob | None:
        return self.store.get(job_id)
